navigation/contour_images_folder: contour_images/
navigation/debug_folder: /debug/
navigation/hsv_lower_red_1:
- 0
- 30
- 30
navigation/hsv_lower_red_2:
- 160
- 30
- 30
navigation/hsv_upper_red_1:
- 10
- 255
- 255
navigation/hsv_upper_red_2:
- 10
- 255
- 255
navigation/image_height: 240
navigation/image_width: 320
navigation/min_contour_area: 100.0
navigation/rate: 20
navigation/raw_images_folder: raw_images/
navigation/x_shift_epsilon: 20
navigation/spin_vel: 3
navigation/forward_vel: 1
navigation/debug: false